# Generated by Django 2.1.7 on 2019-05-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_conditioner', '0002_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailmodel',
            name='temp',
        ),
    ]
